[project]
name = "micrograd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "hypothesis>=6.122.1",
    "matplotlib>=3.9.3",
    "pytest>=8.3.4",
    "scikit-learn>=1.5.2",
    "torch<2.3.0",
]
