[project]
name = "minigpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib<3.10",
    "numpy<2",
    "torch<2.3.0",
    "tqdm>=4.67.1",
]
